version: "3"

services:
  pouch:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: tail -F anything
    links:
      - couchdb
    depends_on:
      - couchdb

  couchdb:
    container_name: couchdb
    hostname: couchdb.local
    image: "apache/couchdb:${DOCKER_TAG:-latest}"
    environment:
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
    volumes:
      - "~/data:/opt/couchdb/data"
    ports:
      - "5984:5984"
