version: "3"

services:
  agronomiapp:
    build: .
    container_name: agronomiapp
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:80
      - 443:443
      - 3000:3000
      - 9229:9229
    command: tail -F anything
    links:
      - couchdb
    depends_on:
      - couchdb

  couchdb:
    build: ./docker-couchdb
    container_name: couchdb
    hostname: couchdb.local
    environment:
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
    volumes:
      - "~/data:/opt/couchdb/data"
    ports:
      - "5984:5984"
      - "6984:6984"
